### PR TITLE
feat: A380 Preview

### PR DESCRIPTION
**Pull request by ErickSharp**
## Summary of changes
Add projects page for the A380 to serve as a preview page for the time being. I made a copy of the components in the A320 projects page and retrofit them to apply to the A380. Waiting for the hero carousel to be merged to use some of the code to create a carousel that displays each released progress photo in addition to an accompanying caption. 

## Screenshots(if applicable)
image

### CODE REVIEW

**Comment by Benjozork** [comment]
image

This sounds kinda corny

**Comment by ErickSharp** [comment]
elote 🤨

**Comment by ErickSharp** [comment]
yeah I know it is out of place we will find something to put in. I just didn't want to be lazy and commit the exact copy of the a32nx projects page.

**Comment by ErickSharp** [comment]
waiting to block out a good base UI for the projects pages, starting with the A32NX so this will be on hold for a bit.

**Pull request closed without merging**
