### PR TITLE
refactor: make scrollbar look nice 🥳

### PR DESCRIPTION
**Pull request by ErickSharp**
## Summary of changes
Change the look of the scrollbar to be slimmer and have our fbw teal!

## Screenshots(if applicable)
< Provide screenshots of the affected areas if applicable to support your changes being made ensuring you show the full scope of the area changed and surrounding content, this allows for faster reviews on PRs. >
BEFORE: 
image

AFTER: 
image

### CODE REVIEW

**Comment by tracernz** [comment]
Not a fan of changing anything other than the colour. Size of the browser UI elements is for the browser+user to decide IMO.

**Comment by ErickSharp** [comment]
> Not a fan of changing anything other than the colour. Size of the browser UI elements is for the browser+user to decide IMO.

I could change the width from 8 to 16, but I tried it out and I personally didn't like it. I think this looks rather good, though.

**Comment by NathanInnes** [comment]
I think we should go for something more like GitHub style, a little thinner and darker. Fully changing the scroll bar is subjective to a lot of people and I have never seen many people ever do it

**Comment by ErickSharp** [comment]
hmm idk I would perhaps need some more input on this but I think its something that is just unique and ties in together with the other themed scrollbars we have going on like those in the efb

**Comment by ErickSharp** [comment]
the installer also has a similarly shaped scrollbar, its just grey-toned which we can do here as well if that's what we think is a better choice

**Comment by armankir** [comment]
Not a fan, it's an eyesore. You can do what Sabes said with the GitHub theme, that would look good.

**Comment by ErickSharp** [comment]
I really think it ties into the overall design and theme of the website, perhaps we can get more input on this? Also, if not this color scheme, would you guys like this scrollbar?

image

**Comment by NathanInnes** [comment]
> the installer also has a similarly shaped scrollbar, its just grey-toned which we can do here as well if that's what we think is a better choice

The difference is, the installer is a piece of desktop software and the default scrollbar is a no go anyways. Websites don't usually receive the same treatment

**Pull request merged**
