### PR TITLE
feat: branding Guidelines

### PR DESCRIPTION
**Pull request by NathanInnes**
Fixes N/A

## Summary of changes
Add branding guidelines to website

## Screenshots(if applicable)
image

image

### CODE REVIEW

**Comment by ErickSharp** [comment]
LgTm

**Comment by NathanInnes** [comment]
Do not merge. Forgot to add link to page

**Comment by armankir** [comment]
> Do not merge. Forgot to add link to page

Are you going to add the link?

**Comment by Benjozork** [comment]
I still need to review it too bruhvs

**Comment by ErickSharp** [comment]
Are you going to add the link 😟

**Pull request closed without merging**
