### PR TITLE
refactor(partners): change layout of the partners section

### PR DESCRIPTION
**Pull request by ErickSharp**
## Summary of changes
Change the layout of the partners section such that on large screen sizes all of the partners occupy the space on an entire row. 

TODO: Change distance between the images in each column to be tighter. Padding is needed but results in the contents of each column shrinking. 

### Desktop Section:
image

### Desktop Full:
image

### iPad Pro:
image

### iPhone X:
image

### JioPhone 2:
image

### CODE REVIEW

**Comment by ErickSharp** [comment]
Will remove the partner consts dw

**Comment by NathanInnes** [comment]
Please stick to using component Partner and PartnerImage as you have a lot of reused classes

**Comment by ErickSharp** [comment]
waiting for svg version of placeholder png

**Comment by ErickSharp** [comment]
> waiting for svg version of placeholder png

KO said to just go ahead with using the png for the time being.

**Pull request merged**
