### PR TITLE
refactor: add ease-in-out transitions to buttons

### PR DESCRIPTION
**Pull request by GhostEagle68**
Fixes #[issue_no]

## Summary of changes
-Added ease-in-out transitions to buttons

### CODE REVIEW

**Review by NathanInnes — CHANGES_REQUESTED** [review]
Please do not outright disable an error when it's telling you exactly what the issue is. 

```
/home/runner/work/website/website/components/home/Discord.tsx
  23:1  error  This line has a length of 203. Maximum allowed is 192  max-len

/home/runner/work/website/website/components/home/Installer.tsx
  20:1  error  This line has a length of 214. Maximum allowed is 192  max-len
``` 
log output.

It's saying that you need to shorten how much text is on a single line on both locations of these files. Do this by putting text on a new line. Example: 
```
**This text is about to be seperated
now**

**Comment by ErickSharp** [comment]
I recommend that you just add the transition and duration properties to the actual `Button.tsx` component as opposed to adding it in the classname of the buttons within each different component.

**Comment by NathanInnes** [comment]
@GhostEagle68 Any update on this PR? I reccomend what @ErickSharp said: 

> I recommend that you just add the transition and duration properties to the actual `Button.tsx` component as opposed to adding it in the classname of the buttons within each different component.

**Comment by ErickSharp** [comment]
For the sake of convenience and simplicity, I put your code in the Button.tsx component and Co-authored you in the pull request. Gonna close this out.

**Pull request closed without merging**
