### PR TITLE
style: navbar logo updated

### PR DESCRIPTION
**Pull request by Spherrrical**
Fixes #[issue_no]

## Summary of changes
Old logo removed and replaced with the newest available logo from branding repo in PNG.

## Screenshots(if applicable)
image

### CODE REVIEW

**Comment by Valastiri** [comment]
favicon could use updating if you'd like to include that

**Comment by Spherrrical** [comment]
Sure thing, I'll create a favicon

**Comment by NathanInnes** [comment]
Issue is that the logo has updated colours and the rest of the website doesn't. Not sure of how the progress of the revamp is coming along

**Comment by Spherrrical** [comment]
Does the pr for revamp v3 include the color changes? If so, we can just move this change into revamp. Let me know your thoughts.

**Pull request closed without merging**
